//import { shaderMaterial, Sparkles, Center, useTexture, useGLTF, OrbitControls } from '@react-three/drei'
import { OrbitControls } from "@react-three/drei";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/model/vending machine.glb");
  return (
    <>
      {/* <OrbitControls makeDefault /> */}
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials["Material.002"]}
          position={[0.173, 2.746, 15.347]}
          scale={[1, 2.728, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.cloud66.geometry}
          material={materials.cloud66}
          position={[0.161, 2.256, 13.701]}
          rotation={[1.578, 0.003, -3.14]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.rubber}
          position={[0.173, 2.746, 15.347]}
          scale={[1, 2.728, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vending_machine.geometry}
          material={materials["vending machine floor"]}
          position={[0, 3.136, -10.808]}
          scale={[1.495, 2.961, 1.676]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.vending_poster001.geometry}
            material={materials["rooty label"]}
            position={[0, 0, 0.015]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials.rubber}
          position={[-0.006, 2.934, -10.787]}
          scale={[1, 2.728, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials.rubber}
          position={[0, 3.136, -10.808]}
          scale={[1.495, 2.961, 1.676]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.vending_machine_window.geometry}
          material={materials["Material.003"]}
          position={[0, 3.136, -10.808]}
          scale={[1.495, 2.961, 1.676]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chip_bag001.geometry}
          material={materials["chip bag"]}
          position={[0.376, 2.733, -10.642]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.527, 0.812, 0.812]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.chip_bag003.geometry}
          material={materials["bbq chips 5"]}
          position={[0.994, 5.24, 5.089]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[0.328, 0.505, 0.505]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.soda_can.geometry}
          material={materials["silver top"]}
          position={[5.357, 4.36, 2.192]}
          scale={[0.134, 0.26, 0.134]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.soda_can_body.geometry}
            material={materials["diet bubblin label"]}
            rotation={[-Math.PI, 1.107, -Math.PI]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.game_case.geometry}
          material={materials.Material}
          position={[17.864, 2.934, 14.048]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.33, 2.465, 1.472]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.coin_slot.geometry}
            material={materials["Material.004"]}
            position={[0.047, 0, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.game_case_buttons.geometry}
            material={materials.rubber}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.game_case001.geometry}
            material={materials["Material.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.joystick.geometry}
            material={materials.joystick}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.joystick001.geometry}
            material={materials.joystick}
            position={[0, 0, -0.68]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.marble_race_2.geometry}
            material={materials["marble race 2"]}
            position={[0.301, 0.293, 0]}
            rotation={[1.402, 0.555, -1.222]}
            scale={[1.229, 1.181, 0.953]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.soda_can001.geometry}
          material={materials["silver top"]}
          position={[5.357, 4.36, 1.255]}
          scale={[0.134, 0.26, 0.134]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.soda_can_body001.geometry}
            material={materials["bubblin label"]}
            rotation={[-Math.PI, 1.107, -Math.PI]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.soda_can002.geometry}
          material={materials["silver top"]}
          position={[5.357, 4.36, -0.225]}
          scale={[0.134, 0.26, 0.134]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.soda_can_body002.geometry}
            material={materials["cool-la"]}
            rotation={[-Math.PI, 1.107, -Math.PI]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.soda_can003.geometry}
          material={materials["silver top"]}
          position={[5.357, 4.36, -1.667]}
          scale={[0.134, 0.26, 0.134]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.soda_can_body003.geometry}
            material={materials["rooty label.001"]}
            rotation={[-Math.PI, 1.107, -Math.PI]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.soda_can004.geometry}
          material={materials["silver top"]}
          position={[-0.184, 3.168, -10.175]}
          scale={[0.134, 0.26, 0.134]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.soda_can_body004.geometry}
            material={materials["zest-up label"]}
            rotation={[-Math.PI, 1.107, -Math.PI]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.separation001.geometry}
          material={materials["silver top"]}
          position={[0, 3.136, -10.808]}
          scale={[1.495, 2.961, 1.676]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vending_Tray.geometry}
          material={materials["cool-la"]}
          position={[0, 2.521, -10.694]}
          rotation={[Math.PI / 2, 1.279, -Math.PI / 2]}
          scale={[1.199, 1.027, 0.977]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vending_Tray001.geometry}
          material={materials["Material.005"]}
          position={[0, 1.64, -10.694]}
          rotation={[Math.PI / 2, 1.279, -Math.PI / 2]}
          scale={[1.199, 1.027, 0.977]}
        />
      </group>
    </>
  );
}

useGLTF.preload("/model/vending machine.glb");
